services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-bot
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - TZ=Asia/Jakarta
    networks:
      - proxy

networks:
  proxy:
    external: true
